# -*- coding: utf-8 -*-
"""WebScrapping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QPARJ2uEhXjcMllNBIn_ITUuP864U83H
"""

!pip install -q google-play-scraper
from google_play_scraper import app, Sort, reviews_all
import pandas as pd
import numpy as np
import json
import datetime
import seaborn as sns
import matplotlib.pyplot as plt

review_data = reviews_all('us.zoom.videomeetings', sleep_milliseconds=0, lang='en', country='US', sort=Sort.NEWEST )

zoom_review = pd.json_normalize(review_data)

zoom_review.head(10)

zoom_review.to_excel('zoom_review.xlsx')

zoom_review.shape

